### ISSUE TITLE
CC0 Licensing

### ISSUE THREAD

**Issue by ufl-taeber** [RASpicer/RASpicer.github.io#2]
Dr Spicer:

I am a Software Engineer from the University of Florida in the US that is working on the [Metabolomics Consortium Coordinating Center (M3C) People Portal](https://people.metabolomics.info/) along with @KevinHanson, @senrabc, and @mconlon17.

Our site uses the data from the Metabolomics Tools Wiki to populate our Tools Listing page. 
As the M3C is publicly-funded by [NIH grant 1U2CDK119889-01](https://projectreporter.nih.gov/project_info_description.cfm?aid=9589555&icde=42187027&ddparam=&ddvalue=&ddsub=&cr=3&csb=default&cs=ASC&pball=), we would like to publish all of our site's data (including your tool data) under a Creative Commons Zero license.

I'm unsure about the details of re-licensing under the current GNU Free Documentation license, but would you be willing to allow us to do so? We plan to use https://zenodo.org/ and will of course add you as an author to the authors list.

Thank you for your work and your consideration!
Taeber

Here's a preview of an upcoming release of the Tools Listing page with facets:
![image](https://user-images.githubusercontent.com/7585041/80240591-1c536100-8630-11ea-8d3d-52901a1abf30.png)

**Comment by RASpicer** [comment]
I'd be happy for the data to be used M3C portal. If you need me to update the license I will do.
